eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8086

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:8082
          predicates:
              - Path=/authentication-service/**
          filters:
              - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
          
        - id: ticket-service
          uri: http://localhost:8083
          predicates:
            - Path=/ticket-service/**
          filters:
            - RewritePath=/ticket-service(?<segment>/?.*), $\{segment}


        - id: search-service
          uri: http://localhost:8085
          predicates:
            - Path=/search-service/**
          filters:
            - RewritePath=/search-service(?<segment>/?.*), $\{segment}

        - id: comment-service
          uri: http://localhost:8084
          predicates:
            - Path=/comment-service/**
          filters:
            - RewritePath=/comment-service(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8087
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}
