server:
  port: 8082
spring:
  datasource:
    password: CSlayer25AUG@
    url: jdbc:mysql://localhost:3306/GLOTMS?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
#eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    fetch-registry: true
